Feat/API-Product
include-davis/Include-Estore-API pull request #18
Opened 2024-03-08 07:29 UTC by RayBipse

## Description
Create Product model and CRUD operations

## Issue
Closes #7

2024-03-10 06:44 UTC, brandonw504 requested changes
Just a few things:
- Rename Product.ts to Products.ts in services, since we want to keep them plural
- Run the migration (should show up in your commit in the migrations folder)
- Remember to test your CRUD operations in the playground
- Maybe make description and details nullable (@Austin2Shih thoughts?)

2024-03-14 17:40 UTC, RayBipse commented
Tested ✅

2024-04-01 02:18 UTC, Austin2Shih commented
@brandonw504 final review and merge if good :)

2024-04-01 03:08 UTC, brandonw504 approved these changes

2024-04-01 03:08 UTC, merged