Feat/User_CRUD_Operations
include-davis/Include-Estore-API pull request #20
Opened 2024-03-27 23:47 UTC by VinBid

* Updated with CRUD Operations for Users
* Tested Operations
**BLOCKERS:**
* The Update Operation does not seem to work if I do not include all the input fields. Otherwise it works. Would be great if someone could look through.

2024-04-01 02:30 UTC, Austin2Shih requested changes
If you need help, refer to Kiran's code which is in another PR at the moment. Sorry I am super busy so you might need to consult other people working on similar tasks for this. However, if ya'll run into huge roadblocks then still feel free to ask me for help.

2024-04-01 02:30 UTC, Austin2Shih commented on src/typeDefs/index.ts
> +
Make sure to get your eslint stuff properly configured. Make sure to not have linting errors or else you won't pass the checks

2024-04-16 18:53 UTC, VinBid reviewed
* Fixed the Issue with the updating of users
* Cleaned up Code to prevent problems

2024-04-24 01:29 UTC, brandonw504 reviewed
I tested all the CRUD operations and everything works great! I'd suggest renaming your migrations to be more descriptive than "migration" and "f" so that in the future we'll know by the title what the migrations did. Other than that, looks good to me!

2024-04-24 01:29 UTC, brandonw504 commented on prisma/dev.db
I looked through this file and dev.db-journal, and I'm not sure what they are, did you add them intentionally? I saw stuff about SQLite but we should be using PostgreSQL, so I just wanted to check with you to make sure.

2024-05-07 20:25 UTC, VinBid commented on prisma/dev.db
That was by accident, probably when I was initially testing things.

2024-05-10 22:03 UTC, brandonw504 commented
I think the last two things to do are deleting dev.db and dev.db-journal and re-running the migrations so that you can give them more descriptive names. After that, we should be good to merge!

2024-12-24 00:28 UTC, closed without merging